# Generated by Django 4.2.7 on 2025-12-25 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('pan_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('residential_address', models.TextField(blank=True)),
                ('residential_city', models.CharField(blank=True, max_length=100)),
                ('residential_state', models.CharField(blank=True, max_length=100)),
                ('residential_country', models.CharField(default='India', max_length=100)),
                ('residential_pincode', models.CharField(blank=True, max_length=10)),
                ('occupation_type', models.CharField(blank=True, choices=[('SALARIED', 'Salaried Employee'), ('SELF_EMPLOYED', 'Self Employed'), ('BUSINESS', 'Business Owner'), ('PROFESSIONAL', 'Professional'), ('RETIRED', 'Retired'), ('STUDENT', 'Student'), ('HOMEMAKER', 'Homemaker'), ('OTHER', 'Other')], max_length=50)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'db_table': 'customers',
            },
        ),
    ]
