# Generated by Django 5.0 on 2025-12-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDrivingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_issue_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('license_status', models.CharField(choices=[('VALID', 'Valid'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='VALID', max_length=20)),
                ('total_years_experience', models.PositiveIntegerField(default=0)),
                ('vehicle_types_driven', models.JSONField(default=list, help_text='List of vehicle types driven')),
                ('violations_count', models.PositiveIntegerField(default=0)),
                ('accidents_count', models.PositiveIntegerField(default=0)),
                ('dui_convictions', models.PositiveIntegerField(default=0)),
                ('last_violation_date', models.DateField(blank=True, null=True)),
                ('last_accident_date', models.DateField(blank=True, null=True)),
                ('suspension_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driving_history', to='customers.customerprofile')),
            ],
            options={
                'db_table': 'customer_driving_history',
            },
        ),
        migrations.CreateModel(
            name='CustomerMedicalDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure_date', models.DateField(auto_now_add=True)),
                ('medical_condition', models.CharField(blank=True, max_length=255)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('is_chronic', models.BooleanField(default=False)),
                ('medication_list', models.TextField(blank=True, help_text='List of current medications')),
                ('hospital_visits_last_year', models.PositiveIntegerField(default=0)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_hypertension', models.BooleanField(default=False)),
                ('has_heart_disease', models.BooleanField(default=False)),
                ('has_cancer_history', models.BooleanField(default=False)),
                ('smoker', models.BooleanField(default=False)),
                ('alcohol_consumption', models.CharField(blank=True, choices=[('NONE', 'None'), ('OCCASIONAL', 'Occasional'), ('REGULAR', 'Regular')], max_length=20)),
                ('is_disclosed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_disclosures', to='customers.customerprofile')),
            ],
            options={
                'db_table': 'customer_medical_disclosures',
                'ordering': ['-disclosure_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_category', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='MEDIUM', max_length=10)),
                ('risk_score', models.DecimalField(decimal_places=2, default=50.0, help_text='Risk score 0-100 (higher = riskier)', max_digits=5)),
                ('age_risk_factor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('medical_risk_factor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('driving_risk_factor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('claim_history_risk_factor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employment_risk_factor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_risk_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Premium adjustment percentage based on risk', max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='customers.customerprofile')),
            ],
            options={
                'db_table': 'customer_risk_profiles',
            },
        ),
        migrations.CreateModel(
            name='ClaimHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_year', models.PositiveIntegerField(db_index=True)),
                ('claim_count', models.PositiveIntegerField(default=0)),
                ('claim_amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('claim_approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('claim_rejection_count', models.PositiveIntegerField(default=0)),
                ('last_claim_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_histories', to='customers.customerprofile')),
            ],
            options={
                'db_table': 'claim_history',
                'ordering': ['-claim_year'],
                'unique_together': {('customer', 'claim_year')},
            },
        ),
    ]
