# Generated by Django 5.0 on 2025-12-26 19:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerdrivinghistory_customermedicaldisclosure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_name', models.CharField(max_length=255)),
                ('fleet_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('fleet_type', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('PRIVATE', 'Private'), ('MIXED', 'Mixed')], default='COMMERCIAL', max_length=20)),
                ('total_vehicles', models.PositiveIntegerField(default=0)),
                ('fleet_ownership_date', models.DateField(blank=True, null=True)),
                ('fleet_purpose', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fleets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleets', to='customers.customerprofile')),
            ],
            options={
                'db_table': 'fleets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FleetRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_risk_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('vehicle_count_factor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('claim_ratio_factor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('fleet_risk_category', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='MEDIUM', max_length=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage for fleet policies', max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fleet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to='customers.fleet')),
            ],
            options={
                'db_table': 'fleet_risk_scores',
            },
        ),
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_registration_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('TRUCK', 'Truck'), ('VAN', 'Van'), ('BUS', 'Bus'), ('MOTORCYCLE', 'Motorcycle'), ('OTHER', 'Other')], default='CAR', max_length=20)),
                ('vehicle_fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default='PETROL', max_length=20)),
                ('vehicle_seating_capacity', models.PositiveIntegerField(default=5)),
                ('vehicle_current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vehicle_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SOLD', 'Sold'), ('SCRAPPED', 'Scrapped')], default='ACTIVE', max_length=20)),
                ('added_at', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.fleet')),
            ],
            options={
                'db_table': 'fleet_vehicles',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='FleetClaimHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_year', models.PositiveIntegerField(db_index=True)),
                ('total_claims', models.PositiveIntegerField(default=0)),
                ('total_claim_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('approved_claim_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('claim_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Claims to premium ratio', max_digits=5)),
                ('settled_claims', models.PositiveIntegerField(default=0)),
                ('rejected_claims', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_histories', to='customers.fleet')),
            ],
            options={
                'db_table': 'fleet_claim_history',
                'ordering': ['-claim_year'],
                'unique_together': {('fleet', 'claim_year')},
            },
        ),
    ]
