# Generated by Django 5.0 on 2025-12-26 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PERMISSION_DENIED', 'Permission Denied'), ('STATUS_CHANGE', 'Status Change'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20),
        ),
        migrations.CreateModel(
            name='DataModificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.CharField(db_index=True, max_length=100)),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('modification_type', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_index=True, max_length=20)),
                ('modification_reason', models.TextField(blank=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_modification_history',
                'ordering': ['-modified_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'modified_at'], name='data_modifi_entity__dc2b77_idx')],
            },
        ),
    ]
