# Generated by Django 4.2.7 on 2025-12-25 10:16

import apps.claims.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(db_index=True, default=apps.claims.models.generate_claim_number, max_length=100, unique=True)),
                ('claim_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('THEFT', 'Theft'), ('NATURAL_DISASTER', 'Natural Disaster'), ('MEDICAL', 'Medical'), ('DEATH', 'Death'), ('DAMAGE', 'Property Damage'), ('LIABILITY', 'Third Party Liability'), ('OTHER', 'Other')], max_length=30)),
                ('claim_description', models.TextField()),
                ('incident_date', models.DateField()),
                ('incident_location', models.TextField(blank=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, help_text='Amount claimed by customer', max_digits=15)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved by Backoffice (must be ≤ amount_requested)', max_digits=15, null=True)),
                ('amount_settled', models.DecimalField(blank=True, decimal_places=2, help_text='Amount actually settled', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SETTLED', 'Settled'), ('CLOSED', 'Closed')], db_index=True, default='SUBMITTED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('review_started_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='customers.customerprofile')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='claims', to='policies.policy')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_claims', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('FIR_COPY', 'FIR Copy'), ('MEDICAL_REPORT', 'Medical Report'), ('HOSPITAL_BILL', 'Hospital Bill'), ('REPAIR_ESTIMATE', 'Repair Estimate'), ('REPAIR_BILL', 'Repair Bill'), ('DAMAGE_PHOTO', 'Damage Photos'), ('POLICE_REPORT', 'Police Report'), ('WITNESS_STATEMENT', 'Witness Statement'), ('ID_PROOF', 'Identity Proof'), ('OTHER', 'Other')], db_index=True, max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='claim_documents/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims.claim')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_claim_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_claim_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claim_documents',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['policy'], name='claims_policy__d2422d_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['customer'], name='claims_custome_d90b87_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='claims_status_cb731f_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['submitted_at'], name='claims_submitt_df2e3f_idx'),
        ),
    ]
