# Generated by Django 5.0 on 2025-12-26 19:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('assessment_location', models.TextField(blank=True)),
                ('assessment_report_url', models.URLField(blank=True)),
                ('damage_assessment', models.TextField(help_text='Description of damage/loss assessed')),
                ('assessment_findings', models.JSONField(default=dict, help_text='Detailed findings in JSON format')),
                ('loss_amount_assessed', models.DecimalField(blank=True, decimal_places=2, help_text='Total loss amount assessed by surveyor', max_digits=15, null=True)),
                ('deductible_applicable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_claim_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Recommended claim amount (loss - deductible)', max_digits=15, null=True)),
                ('assessment_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('UNDER_REVIEW', 'Under Review')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='claims.claim')),
                ('surveyor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='claim_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claim_assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='ClaimSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('settlement_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('DIRECT_REPAIR', 'Direct Repair')], default='BANK_TRANSFER', max_length=20)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=50)),
                ('account_holder_name', models.CharField(blank=True, max_length=255)),
                ('cheque_number', models.CharField(blank=True, max_length=50)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('settlement_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('settlement_reference_number', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('settlement_approved_at', models.DateTimeField(auto_now_add=True)),
                ('settlement_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='claims.claim')),
                ('settlement_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='approved_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claim_settlement',
            },
        ),
        migrations.CreateModel(
            name='ClaimStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('status_change_reason', models.TextField(blank=True)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='claim_status_changes', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='claims.claim')),
            ],
            options={
                'db_table': 'claim_status_history',
                'ordering': ['-status_changed_at'],
                'indexes': [models.Index(fields=['claim', 'status_changed_at'], name='claim_statu_claim_i_b96347_idx')],
            },
        ),
    ]
