# Generated by Django 4.2.7 on 2025-12-25 10:16

import apps.quotes.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('catalog', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(db_index=True, default=apps.quotes.models.generate_quote_number, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='GENERATED', max_length=20)),
                ('base_premium', models.DecimalField(decimal_places=2, max_digits=15)),
                ('risk_adjustment_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('adjusted_premium', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fleet_discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('fleet_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('loyalty_discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('loyalty_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('other_discounts_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('final_premium', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_premium_with_gst', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=15)),
                ('policy_tenure_months', models.PositiveIntegerField(default=12)),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_at', models.DateTimeField()),
                ('overall_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overall suitability score (0-100)', max_digits=5)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='applications.insuranceapplication')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='customers.customerprofile')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_quotes', to=settings.AUTH_USER_MODEL)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='quotes', to='catalog.insurancecompany')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='quotes', to='catalog.insurancetype')),
            ],
            options={
                'db_table': 'quotes',
                'ordering': ['-overall_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_rank', models.PositiveIntegerField()),
                ('recommendation_reason', models.TextField(blank=True)),
                ('suitability_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('affordability_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('coverage_match_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('company_rating_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='applications.insuranceapplication')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='customers.customerprofile')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.insurancetype')),
                ('recommended_quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='quotes.quote')),
            ],
            options={
                'db_table': 'quote_recommendations',
                'ordering': ['recommendation_rank'],
                'unique_together': {('application', 'recommendation_rank')},
            },
        ),
        migrations.CreateModel(
            name='QuoteCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('coverage_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_selected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coverage_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.coveragetype')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='quotes.quote')),
            ],
            options={
                'db_table': 'quote_coverage_selection',
                'unique_together': {('quote', 'coverage_type')},
            },
        ),
        migrations.CreateModel(
            name='QuoteAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.rideraddon')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='quotes.quote')),
            ],
            options={
                'db_table': 'quote_addon_selection',
                'unique_together': {('quote', 'addon')},
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['application'], name='quotes_applica_63801c_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['customer'], name='quotes_custome_3e118e_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='quotes_status_b396a9_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['expiry_at'], name='quotes_expiry__f0aed5_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['overall_score'], name='quotes_overall_a2d2c6_idx'),
        ),
    ]
