# Generated by Django 4.2.7 on 2025-12-25 10:16

import apps.policies.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0001_initial'),
        ('customers', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(db_index=True, default=apps.policies.models.generate_policy_number, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('LAPSED', 'Lapsed')], db_index=True, default='ACTIVE', max_length=20)),
                ('policy_start_date', models.DateField()),
                ('policy_end_date', models.DateField()),
                ('policy_tenure_months', models.PositiveIntegerField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_premium_with_gst', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=15)),
                ('policy_version', models.PositiveIntegerField(default=1)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('last_renewal_date', models.DateField(blank=True, null=True)),
                ('next_renewal_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='customers.customerprofile')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='policies', to='catalog.insurancecompany')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='policies', to='catalog.insurancetype')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_policies', to=settings.AUTH_USER_MODEL)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='policy', to='quotes.quote')),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'db_table': 'policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(db_index=True, default=apps.policies.models.generate_payment_number, max_length=100, unique=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('NET_BANKING', 'Net Banking'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('transaction_reference', models.CharField(blank=True, max_length=255)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('failed_reason', models.TextField(blank=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customerprofile')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='policies.policy')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='quotes.quote')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, default=apps.policies.models.generate_invoice_number, max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('invoice_url', models.URLField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='policies.payment')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='policies.policy')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['customer'], name='policies_custome_09148f_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['status'], name='policies_status_d09338_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_start_date'], name='policies_policy__7c9c02_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_end_date'], name='policies_policy__38d052_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['quote'], name='payments_quote_i_bfccca_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer'], name='payments_custome_8fefc3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_payment_aebcb7_idx'),
        ),
    ]
