# Generated by Django 4.2.7 on 2025-12-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_payment_aebcb7_idx',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='failed_reason',
            new_name='failure_reason',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_reference',
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('NET_BANKING', 'Net Banking'), ('UPI', 'UPI')], default='RAZORPAY', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_order_id'], name='payments_razorpa_c67522_idx'),
        ),
    ]
