# Generated by Django 4.2.7 on 2025-12-25 10:16

import apps.applications.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(db_index=True, default=apps.applications.models.generate_application_number, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('application_data', models.JSONField(blank=True, default=dict, help_text='Dynamic form data based on insurance type')),
                ('requested_coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('policy_tenure_months', models.PositiveIntegerField(default=12)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('review_start_date', models.DateTimeField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='customers.customerprofile')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to='catalog.insurancetype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurance_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID_PROOF', 'Identity Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('PAN_CARD', 'PAN Card'), ('AADHAR_CARD', 'Aadhaar Card'), ('DRIVING_LICENSE', 'Driving License'), ('VEHICLE_RC', 'Vehicle RC'), ('PREVIOUS_POLICY', 'Previous Policy'), ('MEDICAL_REPORT', 'Medical Report'), ('INCOME_PROOF', 'Income Proof'), ('OTHER', 'Other')], db_index=True, max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='application_documents/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.insuranceapplication')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_documents',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddIndex(
            model_name='insuranceapplication',
            index=models.Index(fields=['customer'], name='insurance_a_custome_483043_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceapplication',
            index=models.Index(fields=['insurance_type'], name='insurance_a_insuran_22ce84_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceapplication',
            index=models.Index(fields=['status'], name='insurance_a_status_b0bc10_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceapplication',
            index=models.Index(fields=['submission_date'], name='insurance_a_submiss_66e26d_idx'),
        ),
    ]
