# Generated by Django 5.0 on 2025-12-26 19:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRiskAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_date', models.DateField(db_index=True, unique=True)),
                ('low_risk_count', models.PositiveIntegerField(default=0)),
                ('medium_risk_count', models.PositiveIntegerField(default=0)),
                ('high_risk_count', models.PositiveIntegerField(default=0)),
                ('critical_risk_count', models.PositiveIntegerField(default=0)),
                ('average_risk_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('low_risk_avg_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('high_risk_avg_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_risk_analytics',
                'ordering': ['-analytics_date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_date', models.DateField(db_index=True, unique=True)),
                ('gross_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('gst_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_payments_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('payments_pending', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('payments_failed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('claims_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('successful_payments', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'revenue_analytics',
                'ordering': ['-analytics_date'],
            },
        ),
        migrations.CreateModel(
            name='ClaimAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_date', models.DateField(db_index=True)),
                ('claims_submitted', models.PositiveIntegerField(default=0)),
                ('claims_approved', models.PositiveIntegerField(default=0)),
                ('claims_rejected', models.PositiveIntegerField(default=0)),
                ('claims_settled', models.PositiveIntegerField(default=0)),
                ('claims_pending', models.PositiveIntegerField(default=0)),
                ('total_claimed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_approved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('average_claim_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('claim_approval_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=5)),
                ('claim_settlement_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=5)),
                ('average_processing_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_analytics', to='catalog.insurancetype')),
            ],
            options={
                'db_table': 'claim_analytics',
                'ordering': ['-analytics_date'],
                'unique_together': {('analytics_date', 'insurance_type')},
            },
        ),
        migrations.CreateModel(
            name='PolicyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_date', models.DateField(db_index=True)),
                ('policies_issued', models.PositiveIntegerField(default=0)),
                ('policies_active', models.PositiveIntegerField(default=0)),
                ('policies_expired', models.PositiveIntegerField(default=0)),
                ('policies_cancelled', models.PositiveIntegerField(default=0)),
                ('policies_renewed', models.PositiveIntegerField(default=0)),
                ('total_sum_insured', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_premium_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('average_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_analytics', to='catalog.insurancecompany')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_analytics', to='catalog.insurancetype')),
            ],
            options={
                'db_table': 'policy_analytics',
                'ordering': ['-analytics_date'],
                'unique_together': {('analytics_date', 'insurance_type', 'insurance_company')},
            },
        ),
    ]
