# Generated by Django 4.2.7 on 2025-12-25 10:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('company_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('headquarters_address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('claim_settlement_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.90'), help_text='Claim settlement ratio (0-1)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('service_rating', models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='Service rating out of 5', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Insurance companies',
                'db_table': 'insurance_companies',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('type_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'insurance_types',
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='RiderAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_name', models.CharField(max_length=255)),
                ('addon_code', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('premium_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Premium as percentage of base premium', max_digits=5)),
                ('is_optional', models.BooleanField(default=True)),
                ('max_coverage_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum coverage amount for this add-on', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='addons', to='catalog.insurancetype')),
            ],
            options={
                'db_table': 'riders_addons',
                'ordering': ['insurance_type', 'addon_name'],
                'unique_together': {('insurance_type', 'addon_code')},
            },
        ),
        migrations.CreateModel(
            name='CoverageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_name', models.CharField(max_length=255)),
                ('coverage_code', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('base_premium_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base premium per coverage unit', max_digits=12)),
                ('unit_of_measurement', models.CharField(blank=True, default='per policy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='coverage_types', to='catalog.insurancetype')),
            ],
            options={
                'db_table': 'coverage_types',
                'ordering': ['insurance_type', 'coverage_name'],
                'unique_together': {('insurance_type', 'coverage_code')},
            },
        ),
    ]
