# Generated by Django 5.0 on 2025-12-26 19:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('config_value', models.TextField()),
                ('config_type', models.CharField(choices=[('GENERAL', 'General'), ('QUOTE', 'Quote Settings'), ('CLAIM', 'Claim Settings'), ('PAYMENT', 'Payment Settings'), ('SECURITY', 'Security Settings'), ('TAX', 'Tax Settings')], default='GENERAL', max_length=20)),
                ('config_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('min_value', models.CharField(blank=True, max_length=255)),
                ('max_value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_configuration',
                'ordering': ['config_type', 'config_key'],
            },
        ),
        migrations.CreateModel(
            name='ClaimApprovalThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.CharField(choices=[('AUTO_APPROVE', 'Auto Approve'), ('OFFICER_APPROVAL', 'Officer Approval'), ('MANAGER_APPROVAL', 'Manager Approval'), ('DIRECTOR_APPROVAL', 'Director Approval')], max_length=30)),
                ('min_claim_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('max_claim_amount', models.DecimalField(decimal_places=2, default=Decimal('9999999999.99'), max_digits=15)),
                ('max_processing_days', models.PositiveIntegerField(default=15, help_text='SLA for claim processing')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_thresholds', to='catalog.insurancetype')),
                ('required_approver_role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='claim_thresholds', to='accounts.role')),
            ],
            options={
                'db_table': 'claim_approval_thresholds',
                'ordering': ['insurance_type', 'min_claim_amount'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('rule_condition', models.JSONField(default=dict, help_text='JSON conditions for discount eligibility')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount cap', max_digits=15, null=True)),
                ('rule_priority', models.PositiveIntegerField(default=0, help_text='Higher priority evaluated first')),
                ('is_combinable', models.BooleanField(default=True, help_text='Can this discount combine with others?')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discount_rules', to=settings.AUTH_USER_MODEL)),
                ('insurance_type', models.ForeignKey(blank=True, help_text='Null = applies to all insurance types', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_rules', to='catalog.insurancetype')),
            ],
            options={
                'db_table': 'discount_rules',
                'ordering': ['-rule_priority', 'rule_name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyEligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_condition', models.JSONField(default=dict, help_text='JSON conditions: {min_age, max_age, min_income, etc.}')),
                ('rule_priority', models.PositiveIntegerField(default=0, help_text='Higher priority rules evaluated first')),
                ('error_message', models.CharField(blank=True, help_text='Message to show when rule fails', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='catalog.insurancetype')),
            ],
            options={
                'db_table': 'policy_eligibility_rules',
                'ordering': ['insurance_type', '-rule_priority'],
            },
        ),
        migrations.CreateModel(
            name='CompanyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=255)),
                ('config_value', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='catalog.insurancecompany')),
            ],
            options={
                'db_table': 'company_configuration',
                'ordering': ['insurance_company', 'config_key'],
                'unique_together': {('insurance_company', 'config_key')},
            },
        ),
        migrations.CreateModel(
            name='PremiumSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab_name', models.CharField(max_length=255)),
                ('min_coverage_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('max_coverage_amount', models.DecimalField(decimal_places=2, default=Decimal('9999999999.99'), max_digits=15)),
                ('base_premium', models.DecimalField(decimal_places=2, help_text='Base premium for this slab', max_digits=12)),
                ('percentage_markup', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional percentage of coverage amount', max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_slabs', to='catalog.insurancetype')),
            ],
            options={
                'db_table': 'premium_slabs',
                'ordering': ['insurance_type', 'min_coverage_amount'],
                'unique_together': {('insurance_type', 'min_coverage_amount', 'max_coverage_amount')},
            },
        ),
        migrations.CreateModel(
            name='QuoteCalculationWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(help_text='E.g., age_risk_factor, medical_risk_factor', max_length=255)),
                ('factor_weight', models.DecimalField(decimal_places=2, help_text='Weight between 0 and 1', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('factor_calculation_formula', models.TextField(blank=True, help_text='Description of how factor is calculated')),
                ('min_weight_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_weight_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_weights', to='catalog.insurancetype')),
            ],
            options={
                'db_table': 'quote_calculation_weights',
                'ordering': ['insurance_type', 'factor_name'],
                'unique_together': {('insurance_type', 'factor_name')},
            },
        ),
    ]
