# Generated by Django 5.0 on 2025-12-26 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('POLICY_EXPIRY', 'Policy Expiry'), ('RENEWAL_DUE', 'Renewal Due'), ('PAYMENT_DUE', 'Payment Due'), ('DOCUMENT_EXPIRY', 'Document Expiry'), ('CUSTOM', 'Custom Reminder')], db_index=True, max_length=20)),
                ('related_entity_type', models.CharField(help_text="E.g., 'policy', 'payment'", max_length=50)),
                ('related_entity_id', models.PositiveIntegerField()),
                ('reminder_scheduled_for', models.DateTimeField(db_index=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, help_text="E.g., 'daily', 'weekly', '30_days_before'", max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reminders', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scheduled_reminders', to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'scheduled_reminders',
                'ordering': ['reminder_scheduled_for'],
                'indexes': [models.Index(fields=['reminder_status', 'reminder_scheduled_for'], name='scheduled_r_reminde_0639a6_idx'), models.Index(fields=['related_entity_type', 'related_entity_id'], name='scheduled_r_related_2d4118_idx')],
            },
        ),
    ]
